### ISSUE TITLE
how to change internal domain

### ISSUE THREAD

**Issue by jazzyjas** [minhng92/odoo-14-docker-compose#2]
# Change domain
I setup odoo using the docker image, but every time dodo send email aor similar stuff  it sends localhost instead of my desired domain. Where can I specify the preferred domain for odoo to know? I tried editing the http_interface in "etc/odoo.conf" which resulted in errors. Thank you for your help

**Comment by minhng92** [comment]
Hi @jazzyjas , it may be related to web base url in Odoo.

You can try these step to access the parameter:
1. Turn on Debug mode (by adding **?debug=1** to the URL)
2. Settings > Technical > System Parameters
3. Find and change the value of the key **web.base.url** to your domain name.

Hope this way works for you.

![odoo_baseurl](https://user-images.githubusercontent.com/34470011/119372436-82059700-bce1-11eb-8dfd-979dd34fa1d7.png)

**Comment by jazzyjas** [comment]
Thank you very much, this is *exactly* what I needed. Im amazed that you responded so quickly and helpful. I starred the repo, you deserve it.
