### ISSUE TITLE
help with odoo.conf addons path

### ISSUE THREAD

**Issue by JGStyle** [minhng92/odoo-14-docker-compose#4]
# help
## odoo.conf addons_path

con you explain why you set the addons_path to /mnt/extra-addons even though there is none such directory
and
if I want to add my custom add-on where should I put it and is the /mnt/extra-addons path necessary?

_thank you very much for helping_

**Comment by minhng92** [comment]
Hi @JGStyle , "/mnt/extra-addons" is the folder inside docker container, where custom addons will be loaded. Odoo server is also running inside docker container so it's able to access this folder.

In the [docker-compose.yml line 33](https://github.com/minhng92/odoo-14-docker-compose/blob/master/docker-compose.yml#L33), the folder is mounted to [addons](https://github.com/minhng92/odoo-14-docker-compose/tree/master/addons) folder on host.

So you just put your custom addons in _odoo-14-docker-compose/addons_, it's equivalent to putting the addons in "/mnt/extra-addons" (inside container).

**Comment by JGStyle** [comment]
Thank you very much, is there anyway to then check whether the add-on is installed in odoo?

**Comment by JGStyle** [comment]
this was very helpful, thank you
